version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
  excel_host:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./excel:/usr/share/nginx/html:ro
      - ./nginx.excel.conf:/etc/nginx/conf.d/default.conf:ro
